FROM gcc:15.1.0 AS stage1

WORKDIR /app
COPY . .
RUN apt update && apt upgrade -y && apt install -y cmake \
  libxrandr-dev \
  make libxinerama-dev \
  libxcursor-dev \
  libxi-dev \
  git-all \
  freeglut3-dev && mkdir build-web && \
  git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && ./emsdk install latest && ./emsdk activate latest && . ./emsdk_env.sh && \
  cd ../build-web && emcmake cmake -DPLATFORM=Web .. && make
